steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE}
      - -f
      - dbt_runner/Dockerfile
      - .

images:
  - ${_IMAGE}

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE: us-central1-docker.pkg.dev/image-lab-494712/f1/dbt-runner:latest
